services:
  - type: web
    name: saku-chappy
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SYSTEM_PROMPT
        value: "あなたはLINE上で丁寧に応答する日本語アシスタントです。"
    plan: free
